version : '3'
services:
  db:
    build: ./database
    networks:
      - backend
  app:
    build: ./backend
    ports:
      - 5000:5000
    links:
      - db
    networks:
      - backend
      - frontend
  web:
    build: ./proxy
    ports:
      - 443:443
    volumes: 
      - ./proxy/cat:/etc/nginx/certs
    links:
      - app
    networks:
      - frontend


networks:
  frontend:    
  backend:

       