version: '3'
services:
  database:
    build:
      context: ./Database
      dockerfile: dockerfile
    port:
      - "3306:3306"
    networks:
      - backend

  app:
    build:
      context: ./Backend
      dockerfile: dockerfile
    port:
      - "5000:5000"
    networks:
      - frontend
      - backend

  proxy:
    build:
      context: ./Proxy
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
