version: '3'
services:
  database:
    build:
      context: ./Database
      dockerfile: dockerfile
    networks:
      - backend

  app:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - 5000:5000
    links:
      - database
    networks:
      - frontend
      - backend


  proxy:
    build:
      context: ./Proxy
      dockerfile: dockerfile
    ports:
      - 443:443
    volumes:
      - ./proxy/ssl:/etc/nginx/certs
    links:
      - app
    networks:
      - frontend

networks:
  frontend:
  backend:
