version: '3'
services:
  database:
    build: .
      context: ./Database
      dockerfile: dockerfile
    ports:
    - "3306:3306"
    network:
      network2

services:
  backend:
    build: .
      context: ./Backend
      dockerfile: dockerfile
    ports:
    - "5000:5000"
    network:
      network1
      network2

  services:
    proxy:
      build: .
        context: ./Proxy
        dockerfile: dockerfile
      ports:
      - "443:80"
      network:
        network1
