version: '3'
services:
  database:
    build:
      context: ./Database
      dockerfile: dockerfile
    networks:
      - backend

  app:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - 5000:5000
    networks:
      - frontend
      - backend
    links:
      - database

  proxy:
    build:
      context: ./Proxy
      dockerfile: dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/ssl:/etc/nginx/certs
    networks:
      - frontend
    links:
      - app

networks:
  frontend:
  backend:
