version: '3'
services:
  database:
    build:
      context: ./Database
      dockerfile: dockerfile
    ports:
    - "3306:3306"
    network:
      backend

services:
  app:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
    - "5000:5000"
    network:
      frontend
      backend

services:
  proxy:
    build:
      context: ./Proxy
      dockerfile: dockerfile
    ports:
    - "80:443"
      network:
        frontend

networks:
  frontend:
    # Use a custom driver
    driver: custom-driver-1
  backend:
    # Use a custom driver which takes special options
    driver: custom-driver-2
    driver_opts:
      foo: "1"
      bar: "2"
