version: '3'
services:
  database:
    build:
      context: ./Database
      dockerfile: dockerfile
    command: --default-authentication-plugin=mysql_native_password
#    ports:
#      - "5000:3306"
    networks:
      - backend

  app:
    build:
      context: ./Backend
      dockerfile: dockerfile
#    ports:
#      - "5001:5001"
    networks:
      - frontend
      - backend

  proxy:
    build:
      context: ./Proxy
      dockerfile: dockerfile
#    ports:
#      - "80:443"
    networks:
      - frontend

networks:
  frontend:
    # Use a custom driver
    driver: custom-driver-1
  backend:
    # Use a custom driver which takes special options
    driver: custom-driver-2
#    driver_opts:
#      foo: "1"
#      bar: "2"
