version: '3'
services:
  database:
    build:
      context: ./Database
      dockerfile: dockerfile
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "5000:3306"
    networks:
      - backend

  app:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend

  proxy:
    build:
      context: ./Proxy
      dockerfile: dockerfile
    ports:
      - "80:443"
    networks:
      - frontend

networks:
  frontend:
    # Use a custom driver
    driver: bridge
  backend:
    # Use a custom driver which takes special options
    driver: bridge
