FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/config.d/
COPY html /usr/share/nginx/html
COPY ssl/localhost.crt /etc/ssl/
COPY ssl/localhost.key /etc/ssl

EXPOSE 80
EXPOSE 443
